kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: test-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: test-keycloak
spec:
  server: 
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
  repo:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    mountsatoken: true
  ha:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    enabled: false
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 250m
        memory: 1024Mi
  rbac:
    defaultPolicy: role:admin
    policy: |
      p, role:admin, applications, *, */*, allow
      g, admin, role:admin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testoperator
  namespace: test-keycloak
spec:
  source:
    repoURL: 'https://github.com/Pytargopias/testOpenshift.git'
    targetRevision: HEAD
    path: manifests
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-server-admin 
  namespace: test-keycloak
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-server
    namespace: test-keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-application-controller-admin
  namespace: test-keycloak
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: test-keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin