apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-keycloak
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: argocd
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
